Traceback (most recent call last):
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/simulation.py", line 634, in <module>
    main()
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/simulation.py", line 626, in main
    exe_simu(exp_dict)
  File "/home/jdoelger/InfluenzaFitnessInference/code/notebooks/fitnessinference/simulation.py", line 545, in exe_simu
    os.makedirs(temp_folder)
  File "/home/jdoelger/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/jdoelger/InfluenzaFitnessInference/results/simulations/2021Jun19_varN_pop'
