2021-06-19 13:26:59,369 pypet.storageservice.HDF5StorageService INFO     I will use the hdf5 file `/home/jdoelger/InfluenzaFitnessInference/results/simulations/2021Jun19_varN_pop.hdf5`.
2021-06-19 13:26:59,380 pypet.environment.Environment INFO     Environment initialized.
2021-06-19 13:26:59,400 root INFO     Starting Simulation
2021-06-19 13:26:59,401 pypet.environment.Environment INFO     I am preparing the Trajectory for the experiment and initialise the store.
2021-06-19 13:26:59,401 pypet.environment.Environment INFO     Initialising the storage for the trajectory.
2021-06-19 13:26:59,420 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `2021Jun19_varN_pop`.
2021-06-19 13:26:59,420 pypet.storageservice.HDF5StorageService ERROR    Failed storing `Trajectory 2021Jun19_varN_pop (len:6): (config: <class 'pypet.naturalnaming.ConfigGroup'>), (parameters: <class 'pypet.naturalnaming.ParameterGroup'>)`
