2021-06-19 13:29:11,018 pypet.storageservice.HDF5StorageService INFO     I will use the hdf5 file `/home/jdoelger/InfluenzaFitnessInference/results/simulations/2021Jun19_varN_pop_2.hdf5`.
2021-06-19 13:29:11,033 pypet.environment.Environment INFO     Environment initialized.
2021-06-19 13:29:11,052 root INFO     Starting Simulation
2021-06-19 13:29:11,052 pypet.environment.Environment INFO     I am preparing the Trajectory for the experiment and initialise the store.
2021-06-19 13:29:11,052 pypet.environment.Environment INFO     Initialising the storage for the trajectory.
2021-06-19 13:29:11,062 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `2021Jun19_varN_pop_2`.
2021-06-19 13:29:11,062 pypet.storageservice.HDF5StorageService ERROR    Failed storing `Trajectory 2021Jun19_varN_pop_2 (len:6): (config: <class 'pypet.naturalnaming.ConfigGroup'>), (parameters: <class 'pypet.naturalnaming.ParameterGroup'>)`
