2021-06-19 11:41:34,761 pypet.storageservice.HDF5StorageService INFO     I will use the hdf5 file `C:\Users\julia\Documents\Resources\InfluenzaFitnessLandscape\NewApproachFromMarch2021\InfluenzaFitnessInference\results\simulations\2021Jun19_varN_pop.hdf5`.
2021-06-19 11:41:34,763 pypet.environment.Environment INFO     Environment initialized.
2021-06-19 11:41:34,766 root INFO     Starting Simulation
2021-06-19 11:41:34,767 pypet.environment.Environment INFO     I am preparing the Trajectory for the experiment and initialise the store.
2021-06-19 11:41:34,767 pypet.environment.Environment INFO     Initialising the storage for the trajectory.
2021-06-19 11:41:34,791 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `2021Jun19_varN_pop`.
2021-06-19 11:41:34,822 pypet.storageservice.HDF5StorageService INFO     Finished init or meta data update for `2021Jun19_varN_pop`.
2021-06-19 11:41:34,826 pypet.environment.Environment INFO     
************************************************************
STARTING runs of trajectory
`2021Jun19_varN_pop`.
************************************************************

2021-06-19 11:41:34,826 pypet INFO     PROGRESS: Finished 0/6 runs [                    ]  0.0%
2021-06-19 11:41:34,826 pypet INFO     
=========================================
 Starting single run #0 of 6 
=========================================

2021-06-19 11:41:34,829 pypet ERROR    ERROR occurred during a single run! 
Traceback (most recent call last):
  File "C:\Users\julia\Anaconda3\lib\site-packages\pypet\environment.py", line 259, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "C:\Users\julia\Anaconda3\lib\site-packages\pypet\environment.py", line 314, in _single_run
    result = runfunc(traj, *runargs, **kwrunparams)
  File "C:\Users\julia\Documents\Resources\InfluenzaFitnessLandscape\NewApproachFromMarch2021\InfluenzaFitnessInference\code\notebooks\fitnessinference\simulation.py", line 425, in flu_antigen_simulation
    h_model, J_model = fitness_coeff_p24(traj.N_site, traj.N_state)
  File "C:\Users\julia\Documents\Resources\InfluenzaFitnessLandscape\NewApproachFromMarch2021\InfluenzaFitnessInference\code\notebooks\fitnessinference\simulation.py", line 123, in fitness_coeff_p24
    with open(filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\julia\\Documents\\Resources\\InfluenzaFitnessLandscape\\NewApproachFromMarch2021\\InfluenzaFitnessInference\\p24-B-S0.90-Ising-reduced-out-learn.j'
